language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
env:
  global:
  - secure: kkJsBWz+rzyAc5/tM5fe/7e0rAgEqHUPLlQf1J1cO+PQR4vLVxeJnd+KpWwu9WYzsG4PDPzLxsBMziZJTEq0KPvMAHkqutiaCBBXkkTcLwO3+mxDDYFzxp8TA7YVAPA3mOMYWnbcBPhJd3OeQpr5UbD5EAR8GOkrqab9GnMxb1Hsp07Vb66VeENLhAJZiqwiArUGbT0waVI/hVL5mQIMciUfjyJlhjMcL6gGwyfEUWE30jq8EyhrT4pwBIgXP8INxGsk9zAapNChuiieFDiRYH4Ll9I67Wa1jz2WNyexwTaDtOZn1p8QtHPODQvLJy7qHoa2liphkMT9qdMQj0Ubi54HotPnaTSomYbuWyUlFyD1z6w8hspZXpc4I9C4VDiWsK5m2dfcXKiMWpF7JmeD8lp2ohqsMwVlUYbaG/H6lfq3S3WMin4V5xUXAte1ZhlICa3bahJLsdfdeJtZjFYUrWPiRAoQSpJBDuv5aif8oNb6fVgtATZUKv55MTjqWHOZkwAv4srhdLGidZkayfmCfdDKzFik0EapPGZPouUiGLxeCkxehpZUgJNDfKpwH9PMGzEoTI7NiOVUL4x25vslPqgJvlRtBU/FSLUd9Ahwc0N/2r/nIGkauafWgXIMLEcInvh5P2uDyQSIrrrtcnabUSiiRAh7k1vmEAMn64assFU=
  - secure: Q4WbzaWUC7qWlsA48pOl5LgXd92POdFIn/qigx32n3xHY8D7uTHc+tyvOSb6ZXT90rAe0IsspwlnJT2lpvatu++v432H6ttjkIC20DlhiGUfukMazddP5fQYjs8iGCavCX5C6wHfKXRvGYEX4wgsT8TZMP7LNA3moEpjzQrle5qypdhsnzxzEmkX4Om2sS7o7yyQo9TFgUB5RtxDhFJb+Yx3C7kEpr7xv2zSz5IRYFfYEXbLvj8rYiGAhLZ0s2VbWBVI5q0+UhdMiab2RjOGLo0Xp+hBPAodWA9V/E8Rz8GAbUNo2oyvZuGFlw97X4Fice7Ti4Lg62jOxtbfA0McbIsRwgY9q/M0oR7eHrGLN5RlSQOyCcYWBEtZ05Iebhp/LaeHM6r+akc8cXUUmYO9gXTyaDwkvnO5UCUQKgGcAL0KA52FrnKSg/Tz3H7f3Ku9RwEaLxrP8MnE84AZX84jCQ5RIXOwtkPQa0BUjDWYazBTfUkXR/EemKJUlIOgifmN3rgnLQb6mYwl5mVu+ViCOB6ibghHDchGuEiMYG5Dv4diXrbfLh3u80Xv7/5UaAusbmAifvghkj5GtBkfiI77m9qIRD5Lvm9Q0ZBZUQg2oktQr5/anZCWl1MFpQovrfh2WCSZPtyulzt07nBbe4p3j+Vq51asaDhuT+y6jZpFHto=
